#!/bin/bash

# Vehicle Image Sourcing Guide
# This script helps you find and download vehicle images

echo "🚗 Vehicle Image Sourcing for Option B"
echo "========================================"
echo ""
echo "📋 Task: Download 30 vehicle images"
echo "   - 10 Medium difficulty"
echo "   - 20 Hard difficulty"
echo ""
echo "🔍 Best Free Image Sources:"
echo ""
echo "1. Unsplash (https://unsplash.com)"
echo "   - Search: 'ferrari 488 exhaust'"
echo "   - High quality, free license"
echo "   - Download button on each image"
echo ""
echo "2. Pexels (https://pexels.com)"
echo "   - Search: 'lamborghini huracan'"
echo "   - Free for commercial use"
echo "   - Multiple sizes available"
echo ""
echo "3. Pixabay (https://pixabay.com)"
echo "   - Search: 'mclaren 720s'"
echo "   - Free license"
echo "   - Good variety"
echo ""
echo "4. Manufacturer Press Kits"
echo "   - Ferrari: media.ferrari.com"
echo "   - Lamborghini: press.lamborghini.com"
echo "   - McLaren: cars.mclaren.press"
echo ""
echo "📝 Naming Convention:"
echo "   brand-model-year-part.jpg"
echo "   Example: ferrari-488-2020-exhaust.jpg"
echo ""
echo "📤 Upload to S3:"
echo ""
echo "# Medium difficulty"
echo "aws s3 cp alfa-romeo-giulia-2022-grille.jpg \\"
echo "  s3://vehicle-guesser-1764962592/images/vehicles/medium/"
echo ""
echo "# Hard difficulty"
echo "aws s3 cp ferrari-488-2020-exhaust.jpg \\"
echo "  s3://vehicle-guesser-1764962592/images/vehicles/hard/"
echo ""
echo "✅ Quick Start:"
echo "1. Open VEHICLE_IMAGES_NEEDED.md"
echo "2. Search each vehicle on Unsplash/Pexels"
echo "3. Download and rename files"
echo "4. Upload to S3 using commands above"
echo "5. Update expandedVehicleDatabase.js"
echo ""
echo "⏱️  Estimated time: 2-3 hours"
echo ""
echo "💡 Pro tip: Use browser extensions like 'Download All Images'"
echo "   to speed up the process!"
echo ""

# Create download directory
mkdir -p vehicle-images/medium
mkdir -p vehicle-images/hard

echo "📁 Created directories:"
echo "   ./vehicle-images/medium/"
echo "   ./vehicle-images/hard/"
echo ""
echo "Ready to start! 🚀"
